name: Terraform Plan
on:
  pull_request:

jobs:
  plan:
    name: terraform plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_version: "~> 1.8.0"
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init
      - run: terraform fmt -check
      - run: terraform validate

